# permissions for end users to edit terminals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terminal-editor-role
rules:
- apiGroups:
  - terminal.terminal.com
  resources:
  - terminals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terminal.terminal.com
  resources:
  - terminals/status
  verbs:
  - get
